service: exchange-rates

frameworkVersion: '3'

package:
  excludeDevDependencies: true
  patterns:
    - "!./**/**"
    - "src/**"

provider:
  name: aws
  runtime: python3.10
  versionFunctions: false
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:PutItem
          Resource:
            - "Fn::GetAtt": [ratesTable, Arn]

plugins:
  - serverless-python-requirements

custom: ${file(./serverless/custom.yml)}
functions: ${file(./serverless/functions.yml)}
resources: ${file(./serverless/resources.yml)}
