Resources:
  ratesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: kind
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: kind
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      TableName: ${self:service}-rates-table
